version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    environment:
      - PORT=5000
      - MONGO_HOST=db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mongo-data:
    driver: local